"""
HITL Governance Agent — Safe Multi-sig Transaction Drafting

Agents draft unsigned Safe multi-sig transaction payloads and push them
to a Human-In-The-Loop (HITL) breakpoint. No transaction is submitted
to the EVM without explicit M-of-N human approval via the Streamlit UI.

LEGAL NOTICE:
  The agent's role is advisory. It constructs a transaction proposal
  that humans review and sign off on. The cooperative's legal wrapper
  governs what decisions require multi-sig approval and what quorum
  is required. This agent does NOT have signing authority.

LangGraph graph:
  draft_safe_tx → [HITL BREAKPOINT: human_review] → execute_or_reject → [END]

The HITL breakpoint uses LangGraph's interrupt_before mechanism.
The graph is persisted (checkpointed) until a human approves or rejects
via POST /governance/vote.
"""

from __future__ import annotations

from typing import Any

import structlog
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langgraph.graph import END, StateGraph
from langgraph.checkpoint.memory import MemorySaver

from backend.agents.state import GovernanceState
from backend.config import settings
from backend.schemas.glass_box import AgentAction, EthicalImpactLevel

logger = structlog.get_logger(__name__)

AGENT_ID = "governance-agent-v1"

# In-memory checkpointer (replace with Postgres checkpointer in production)
checkpointer = MemorySaver()


# ── Safe transaction builder ───────────────────────────────────────────────────

def _build_safe_tx_draft(
    to: str,
    value_wei: int,
    data: str,
    nonce: int,
    safe_address: str,
    chain_id: int,
) -> dict[str, Any]:
    """
    Constructs an UNSIGNED Safe multi-sig transaction payload.
    This format is compatible with the Safe Transaction Service API
    and the Gnosis Safe UI for human signing.

    The transaction is NOT submitted here. It is stored in `pending_transactions`
    and presented to the steward council for M-of-N approval.
    """
    return {
        "safe":            safe_address,
        "to":              to,
        "value":           str(value_wei),
        "data":            data or "0x",
        "operation":       0,          # 0 = CALL, 1 = DELEGATECALL
        "safeTxGas":       0,          # Use 0 for Safe UI estimation
        "baseGas":         0,
        "gasPrice":        0,
        "gasToken":        "0x0000000000000000000000000000000000000000",
        "refundReceiver":  "0x0000000000000000000000000000000000000000",
        "nonce":           nonce,
        "chainId":         chain_id,
        "_iskander_note":  (
            "This transaction draft was generated by the Governance Agent. "
            "It is UNSIGNED and requires M-of-N steward approval before submission. "
            "Verify all fields against the legal wrapper before signing."
        ),
    }


# ── Nodes ─────────────────────────────────────────────────────────────────────

def draft_safe_tx(state: GovernanceState) -> GovernanceState:
    """
    Node 1: Interpret the governance proposal and draft an unsigned Safe tx.

    Uses Llama 3 to extract structured transaction parameters from a
    natural language proposal, then constructs the Safe tx payload.
    """
    proposal = state.get("proposal") or {}
    description = proposal.get("description", "")

    action = AgentAction(
        agent_id=AGENT_ID,
        action=f"Draft Safe tx for proposal: '{description[:80]}'",
        rationale=(
            "Governance agent translating a human-approved proposal into a "
            "Safe multi-sig transaction draft for steward council review."
        ),
        ethical_impact=EthicalImpactLevel.HIGH,
        payload={"proposal_id": proposal.get("id"), "to": proposal.get("to")},
    )

    # Extract tx parameters — use LLM to parse natural language proposals,
    # or fall back to explicit fields if the proposal is already structured.
    to_address  = proposal.get("to", "0x0000000000000000000000000000000000000000")
    value_wei   = int(proposal.get("value_wei", 0))
    data        = proposal.get("data", "0x")
    nonce       = int(proposal.get("nonce", 0))

    if description and not proposal.get("to"):
        try:
            llm = ChatOllama(base_url=settings.ollama_base_url, model=settings.ollama_model)
            response = llm.invoke([
                SystemMessage(content=(
                    "You are a cooperative governance assistant. "
                    "Extract the recipient address, ETH value in wei, and calldata "
                    "from the following proposal. Respond with only JSON: "
                    '{"to": "0x...", "value_wei": 0, "data": "0x"}'
                )),
                HumanMessage(content=description),
            ])
            import json
            parsed = json.loads(response.content)
            to_address = parsed.get("to", to_address)
            value_wei  = int(parsed.get("value_wei", value_wei))
            data       = parsed.get("data", data)
        except Exception as exc:
            logger.warning("llm_proposal_parse_failed", error=str(exc))

    safe_tx = _build_safe_tx_draft(
        to=to_address,
        value_wei=value_wei,
        data=data,
        nonce=nonce,
        safe_address=settings.safe_address,
        chain_id=settings.evm_chain_id,
    )

    logger.info("safe_tx_drafted", to=to_address, value_wei=value_wei)

    return {
        **state,
        "safe_tx_draft": safe_tx,
        "hitl_approved": None,   # Awaiting human decision
        "action_log":    state.get("action_log", []) + [action.model_dump(mode="json")],
    }


def human_review(state: GovernanceState) -> GovernanceState:
    """
    HITL Breakpoint Node — graph pauses here until a human votes.

    LangGraph's interrupt_before mechanism suspends execution at this node.
    The frontend polls GET /governance/proposals/{id} until hitl_approved
    is set by POST /governance/vote.

    This node is a no-op in the graph; the state mutation happens externally
    via the API endpoint that resumes the graph with the human decision.
    """
    # Execution reaches here only after the human has voted (graph resumed).
    return state


def execute_or_reject(state: GovernanceState) -> GovernanceState:
    """
    Node 3: Route based on HITL decision.

    APPROVED: persist the Safe tx to `pending_transactions` for on-chain submission.
    REJECTED: log the rejection and clear the draft.

    The actual on-chain submission still requires the stewards to manually
    sign via the Safe UI or gnosis-py — this agent does NOT sign.
    """
    approved = state.get("hitl_approved")
    safe_tx  = state.get("safe_tx_draft", {})

    if approved:
        action = AgentAction(
            agent_id=AGENT_ID,
            action="Persist approved Safe tx to pending_transactions ledger",
            rationale="Human quorum approved the governance proposal; queuing unsigned tx for steward signatures.",
            ethical_impact=EthicalImpactLevel.HIGH,
            payload={"safe_address": safe_tx.get("safe"), "to": safe_tx.get("to"), "value": safe_tx.get("value")},
        )
        logger.info("governance_tx_approved", to=safe_tx.get("to"))
        # TODO Phase 5: persist to Postgres `pending_transactions` via SQLAlchemy
    else:
        action = AgentAction(
            agent_id=AGENT_ID,
            action="Reject governance proposal — clear Safe tx draft",
            rationale=f"Proposal rejected by human stewards. Reason: {state.get('rejection_reason', 'not provided')}",
            ethical_impact=EthicalImpactLevel.MEDIUM,
            payload={"rejection_reason": state.get("rejection_reason")},
        )
        logger.info("governance_tx_rejected", reason=state.get("rejection_reason"))

    return {
        **state,
        "action_log": state.get("action_log", []) + [action.model_dump(mode="json")],
    }


# ── Graph assembly ────────────────────────────────────────────────────────────

def build_governance_graph() -> Any:
    g = StateGraph(GovernanceState)
    g.add_node("draft_safe_tx",      draft_safe_tx)
    g.add_node("human_review",       human_review)
    g.add_node("execute_or_reject",  execute_or_reject)

    g.set_entry_point("draft_safe_tx")
    g.add_edge("draft_safe_tx",     "human_review")
    g.add_edge("human_review",      "execute_or_reject")
    g.add_edge("execute_or_reject", END)

    # HITL: interrupt BEFORE human_review so the graph suspends for human input
    return g.compile(
        checkpointer=checkpointer,
        interrupt_before=["human_review"],
    )


governance_graph = build_governance_graph()
