"""
First-Boot Constitutional Dialogue — FastAPI router.

POST /constitution/generate
  Accepts a CoopProfile, renders a Ricardian constitution in Markdown,
  and uploads it to IPFS (mocked in dev via env flag).

The returned IPFS CID must be passed to CoopIdentity.sol's constructor
as `legalWrapperCID` to bind the on-chain identity to the off-chain
legal wrapper. The contract does NOT replace that legal instrument.
"""

from __future__ import annotations

import hashlib
import textwrap
from datetime import datetime, timezone

import structlog
from fastapi import APIRouter, HTTPException, status

from backend.config import settings
from backend.schemas.glass_box import (
    AgentAction,
    CoopProfile,
    ConstitutionResponse,
    EthicalImpactLevel,
)

logger = router_log = structlog.get_logger(__name__)

router = APIRouter(prefix="/constitution", tags=["constitution"])


# ── Constitution template ──────────────────────────────────────────────────────

def _render_constitution(profile: CoopProfile, generated_at: str) -> str:
    principles_block = "\n".join(
        f"- {p}" for p in profile.ica_principles
    ) or "_(none selected — review before ratification)_"

    members_block = "\n".join(
        f"- {m}" for m in profile.founding_members
    )

    return textwrap.dedent(f"""\
        # {profile.coop_name} — Ricardian Constitution
        > **Generated by Project Iskander Sovereign Node**
        > Date: {generated_at}
        > Jurisdiction: {profile.jurisdiction}
        > Legal Wrapper Type: {profile.legal_wrapper_type}

        ---

        ## Preamble

        This document constitutes the foundational legal and operational agreement
        of **{profile.coop_name}**, a cooperative entity incorporated under the
        laws of **{profile.jurisdiction}**.

        > ⚠️ LEGAL NOTICE: This generated document is a STARTING TEMPLATE, not a
        > substitute for qualified legal counsel. Before ratification, it MUST be
        > reviewed by a lawyer familiar with cooperative law in {profile.jurisdiction}.
        > The on-chain representation of this document (IPFS CID) is an extension
        > of this legal instrument, not a replacement for it.

        ---

        ## Article I — Mission

        {profile.mission_statement}

        ---

        ## Article II — Membership

        Membership is open to any individual who:
        1. Agrees to the terms of this Constitution.
        2. Has their membership attested on-chain via the CoopIdentity contract
           (ERC-4973 Account-Bound Token), binding their W3C DID to this legal wrapper.
        3. Participates in at least one of the three DisCO contributory streams:
           Livelihood Work, Care Work, or Commons Work.

        ### Founding Members
        {members_block}

        ---

        ## Article III — Governance

        All significant decisions require a proposal, deliberation period, and
        ratification by the membership via the Iskander HITL Governance API.
        Treasury actions above the steward threshold require M-of-N Safe multi-sig
        approval. No AI agent may execute treasury transactions autonomously.

        ---

        ## Article IV — Compensation & Pay Ratio

        The cooperative adopts a **{profile.pay_ratio}:1** pay ratio cap
        (highest-to-lowest annualised compensation), enforced on-chain by the
        `InternalPayroll` smart contract. Any payment exceeding this ratio will
        revert; the revert is logged to the cooperative's Postgres ledger and
        reviewed by the steward council before re-routing.

        ---

        ## Article V — Committed ICA Cooperative Principles

        {principles_block}

        ---

        ## Article VI — Dissolution

        In the event of dissolution, remaining assets shall be distributed to
        member cooperatives or donated to aligned commons projects, per the
        Asset Lock provisions of this legal wrapper and applicable law in
        {profile.jurisdiction}.

        ---

        ## Article VII — Amendments

        Amendments to this Constitution require a supermajority (≥ 2/3) vote
        of active members. Each amendment creates a new IPFS CID; the CoopIdentity
        contract must be redeployed or upgraded to reference the updated CID.

        ---

        *This document is stored immutably on IPFS. Its CID is the canonical
        reference for the cooperative's legal wrapper and must match the
        `legalWrapperCID` field of the deployed CoopIdentity smart contract.*
    """)


# ── IPFS upload (real or mocked) ──────────────────────────────────────────────

async def _upload_to_ipfs(content: str) -> str:
    """
    Upload constitution markdown to IPFS.
    In dev (IPFS_API_URL unreachable), returns a deterministic mock CID
    derived from the content hash so tests remain reproducible.
    """
    try:
        import ipfshttpclient  # type: ignore
        client = ipfshttpclient.connect(settings.ipfs_api_url, session=False)
        result = client.add_str(content)
        return result  # returns CID string
    except Exception as exc:
        logger.warning("ipfs_unavailable_using_mock_cid", error=str(exc))
        # Deterministic mock CID: sha256 → base58-like prefix
        digest = hashlib.sha256(content.encode()).hexdigest()[:44]
        return f"bafymock{digest}"


# ── Endpoint ───────────────────────────────────────────────────────────────────

@router.post(
    "/generate",
    response_model=ConstitutionResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate and pin a Ricardian constitution to IPFS",
)
async def generate_constitution(profile: CoopProfile) -> ConstitutionResponse:
    """
    First-Boot Constitutional Dialogue endpoint.

    Accepts a cooperative profile, renders a Ricardian constitution in Markdown,
    uploads it to IPFS (or returns a mock CID in dev), and returns the CID
    to be passed into `CoopIdentity.sol`'s constructor.

    **This endpoint must only be called once per cooperative deployment.**
    Subsequent constitutional amendments require a new deployment of
    CoopIdentity with the updated CID.
    """
    generated_at = datetime.now(timezone.utc).isoformat()

    constitution_md = _render_constitution(profile, generated_at)

    cid = await _upload_to_ipfs(constitution_md)

    action = AgentAction(
        agent_id="constitution-agent-v1",
        action=f"Generate and pin constitution for '{profile.coop_name}'",
        rationale=(
            f"First-boot dialogue completed for {profile.coop_name}. "
            f"Constitution rendered with {len(profile.founding_members)} founding member(s), "
            f"{profile.pay_ratio}:1 pay ratio, jurisdiction: {profile.jurisdiction}."
        ),
        ethical_impact=EthicalImpactLevel.HIGH,
        payload={
            "coop_name":   profile.coop_name,
            "ipfs_cid":    cid,
            "member_count": len(profile.founding_members),
        },
    )

    logger.info(
        "constitution_generated",
        coop=profile.coop_name,
        cid=cid,
        action_id=str(action.action_id),
    )

    return ConstitutionResponse(
        constitution_markdown=constitution_md,
        ipfs_cid=cid,
        ipfs_uri=f"ipfs://{cid}",
        agent_action=action,
    )


@router.get(
    "/template",
    summary="Preview a blank constitution template",
)
async def get_template() -> dict:
    """Returns the CoopProfile schema so the frontend can render a guided form."""
    return CoopProfile.model_json_schema()
