"""
Phase 18: Pydantic schemas for the Iterated Prisoner's Dilemma Auditing System.

Request/response models for:
  - Pre-trade cooperation prediction
  - Post-trade outcome recording
  - Reputation profile queries
  - Peer attestation submission
  - Inter-node audit requests
"""
from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


# ── Pre-Trade Prediction ────────────────────────────────────────────────────


class PredictionRequest(BaseModel):
    """Request a pre-trade cooperation probability prediction."""

    partner_did: str = Field(
        ..., description="DID or address of the trading partner."
    )
    is_meatspace: bool = Field(
        default=False,
        description=(
            "True if the partner is a meatspace entity with no on-chain presence. "
            "Redistributes on-chain signal weights to available soft signals."
        ),
    )
    escrow_value: str | None = Field(
        None, description="Trade value for context (e.g., '5000 USDC')."
    )
    sector: str | None = Field(
        None, description="Sector context (e.g., 'organic grain supply')."
    )


class PredictionResponse(BaseModel):
    """Pre-trade cooperation prediction result."""

    partner_did: str
    cooperation_probability: float = Field(
        ..., ge=0.0, le=1.0,
        description="P(cooperate) — weighted signal aggregation.",
    )
    recommended_strategy: str = Field(
        ..., description="GTfT output: 'cooperate' or 'defect'.",
    )
    strategy_rationale: str = Field(
        ..., description="Plain-language explanation of the recommendation.",
    )
    payoff_matrix: dict[str, float] = Field(
        ..., description="{'R': ..., 'S': ..., 'T': ..., 'P': ...} payoff values.",
    )
    expected_values: dict[str, float] = Field(
        ..., description="{'EV_cooperate': ..., 'EV_defect': ...}.",
    )
    forgiveness_rate: float = Field(
        ..., description="GTfT forgiveness probability used in this prediction.",
    )
    signals_used: dict[str, float] = Field(
        default_factory=dict,
        description="Signal name → value map used in the aggregation.",
    )
    requires_human_review: bool = Field(
        ..., description="True when cooperation_probability < floor.",
    )
    is_meatspace: bool
    risk_assessment: dict[str, Any] | None = None
    disclaimer: str = (
        "This prediction is a TRANSPARENCY TOOL generated by the IPD Auditor Agent. "
        "The cooperative's democratic body makes the final trading decision. "
        "Strategy: Generous Tit-for-Tat. Start cooperative, mirror last move, "
        "forgive defections with the disclosed probability."
    )


# ── Post-Trade Outcome Recording ────────────────────────────────────────────


class OutcomeRecordRequest(BaseModel):
    """Record the outcome of an escrow trade for the reputation graph."""

    escrow_id: str = Field(..., description="On-chain escrow identifier.")
    buyer_did: str = Field(..., description="DID or address of the buyer.")
    seller_did: str = Field(..., description="DID or address of the seller.")
    escrow_outcome: str = Field(
        ..., description="One of: Released, Disputed, Arbitrated, Expired.",
    )
    arbitration_outcome: str | None = Field(
        None,
        description="If Arbitrated: buyer_favored, seller_favored, split, dismissed.",
    )
    is_meatspace: bool = Field(
        default=False,
        description="True if this trade involved a meatspace partner.",
    )


class OutcomeRecordResponse(BaseModel):
    """Confirmation after recording a trade outcome."""

    escrow_id: str
    buyer_action: str = Field(..., description="Classified action: cooperate or defect.")
    seller_action: str = Field(..., description="Classified action: cooperate or defect.")
    buyer_updated_reputation: dict[str, Any] | None = None
    seller_updated_reputation: dict[str, Any] | None = None
    message: str


# ── Reputation Profile ──────────────────────────────────────────────────────


class ReputationProfile(BaseModel):
    """Aggregated reputation profile for a cooperative node."""

    node_did: str
    total_interactions: int = 0
    cooperate_count: int = 0
    defect_count: int = 0
    cooperation_ratio: float = 0.0
    avg_response_time_sec: float | None = None
    jury_participation_rate: float = 0.0
    audit_compliance_rate: float = 1.0
    federation_uptime: float | None = None
    is_meatspace: bool = False
    peer_attestation_avg: float = 0.0
    trust_score_on_chain: int | None = Field(
        None, description="On-chain trust score from CoopIdentity.sol (0-1000).",
    )
    updated_at: datetime | None = None


# ── Peer Attestation ────────────────────────────────────────────────────────


class PeerAttestationRequest(BaseModel):
    """Submit a meatspace peer attestation for a trading partner."""

    attester_did: str = Field(..., description="DID of the attesting cooperative.")
    subject_did: str = Field(..., description="DID of the partner being attested.")
    attestation_type: str = Field(
        ...,
        description="One of: delivery_confirmed, quality_verified, ica_compliance, general.",
    )
    score: int = Field(
        ..., ge=0, le=100, description="Attestation score (0-100).",
    )
    comment: str | None = Field(None, description="Optional plain-text comment.")
    escrow_id: str | None = Field(
        None, description="Linked escrow ID, if applicable.",
    )


# ── Inter-Node Audit Request ───────────────────────────────────────────────


class AuditRequestCreate(BaseModel):
    """Request an inter-node audit of a trading partner's reputation."""

    target_node_did: str = Field(
        ..., description="DID of the node being audited.",
    )
    audit_type: str = Field(
        default="reputation_verification",
        description="Type of audit (e.g., reputation_verification, trade_history).",
    )
    reason: str | None = Field(
        None, description="Optional reason for the audit request.",
    )


# ── Pairwise History ───────────────────────────────────────────────────────


class PairwiseHistory(BaseModel):
    """Pairwise cooperation statistics between two nodes."""

    node_a: str
    node_b: str
    total_interactions: int = 0
    mutual_cooperate: int = 0
    a_defect_b_cooperate: int = 0
    b_defect_a_cooperate: int = 0
    mutual_defect: int = 0
    last_a_action: str | None = None
    last_b_action: str | None = None
