{{- if .Values.namespace.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "iskander.fullname" . }}-quota
  namespace: {{ include "iskander.namespace" . }}
  labels:
    {{- include "iskander.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.namespace.resourceQuota.hard | nindent 4 }}
{{- end }}
